language: php
php:
  - 5.3
before_script:
  - pear channel-discover pear.phpunit.de
  - pear channel-discover public.intraface.dk
  - pear install PHP_CodeSniffer
  - pear install intrafacepublic/Ilib_ClassLoader-0.1.2
  - phpenv rehash
script: 
  - phpunit ./tests
  - phpcs src

